# Generated by Django 3.0.1 on 2019-12-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='secure',
            new_name='isSFTP',
        ),
    ]
